### ISSUE TITLE
22-23 Lead 프로필 페이지 라우팅 문제가 있습니다.

### ISSUE THREAD

**Issue by minusmo** [GDSC-CAU/GDSC-CAU.github.io#58]
슬러그 문제인것 같은데 제가 픽스하겠습니다. ㅎ

**Comment by thepenielcho** [comment]
ㅋㅋㅋ본 이슈 포함 여러 버그가 있을 겁니다...ㅋㅋㅋㅋㅋ
호준님과 2기분들이 잡아주시길 바라며... 이슈는 클로즈합니다!
